data_h5: data.hdf5
train_dev: label/traindev_2.csv
test: label/test_2.csv
outputdir: experiments/fusion
Net: densenet.th
Net_lr: 0.0004
other_lr: 0.0004
model: ConvolutionFusion
time_step: 8
dataloader_param:
  batch_size: 4
  num_workers: 4
model_param:
    #bidirectional: True
    #num_layers: 2
    #hidden_size: 512
    #dropout: 0.1
    Net_grad: True
    #nhead: 1
    #n_layer: 1
    #n_dim: 1024
    #n_layer: 1
grad_clip: 10
n_class: 10
optim: Adam
lr_scheduler: ReduceLROnPlateau
Loss: BCELoss
n_epoch: 60
saveinterval: 10
threshold: 0.5
scheduler_param:
  mode: min
  factor: 0.5
  patience: 5
  cooldown: 1
  verbose: False
  threshold: 0.001
  
